
version: '3.8'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=<your-password-here>
      - MONGO_INITDB_ROOT_DATABASE=admin
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"